.PHONY: clean All

All:
	@echo "----------Building project:[ Mizan_Class - Debug ]----------"
	@cd "Mizan_Class" && "$(MAKE)" -f  "Mizan_Class.mk"
clean:
	@echo "----------Cleaning project:[ Mizan_Class - Debug ]----------"
	@cd "Mizan_Class" && "$(MAKE)" -f  "Mizan_Class.mk" clean
